### ISSUE TITLE
Inference Error: Tacotron_kss + MB-MelGAN

### ISSUE THREAD

**Issue by jun-danieloh** [TensorSpeech/TensorFlowTTS#271]
I am trying to load my h5 file for KSS inference but got errors as below. Can you give me a hint to debug? Looks like dimension issues but I didn't change any dimensions myself. Thanks you in advance.

```
tacotron2.load_weights("../examples/tacotron2/exp/train.tacotron2.v1_kss/checkpoints/model-132000.h5")
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-c936c3e287df> in <module>
----> 1 tacotron2.load_weights("../examples/tacotron2/exp/train.tacotron2.v1_kss/checkpoints/model-132000.h5")

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in load_weights(self, filepath, by_name, skip_mismatch)
    248         raise ValueError('Load weights is not yet supported with TPUStrategy '
    249                          'with steps_per_run greater than 1.')
--> 250     return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
    251 
    252   def compile(self,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py in load_weights(self, filepath, by_name, skip_mismatch)
   1264             f, self.layers, skip_mismatch=skip_mismatch)
   1265       else:
-> 1266         hdf5_format.load_weights_from_hdf5_group(f, self.layers)
   1267 
   1268   def _updated_config(self):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in load_weights_from_hdf5_group(f, layers)
    705                        str(len(weight_values)) + ' elements.')
    706     weight_value_tuples += zip(symbolic_weights, weight_values)
--> 707   K.batch_set_value(weight_value_tuples)
    708 
    709 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py in batch_set_value(tuples)
   3382   if ops.executing_eagerly_outside_functions():
   3383     for x, value in tuples:
-> 3384       x.assign(np.asarray(value, dtype=dtype(x)))
   3385   else:
   3386     with get_graph().as_default():

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py in assign(self, value, use_locking, name, read_value)
    844     with _handle_graph(self.handle):
    845       value_tensor = ops.convert_to_tensor(value, dtype=self.dtype)
--> 846       self._shape.assert_is_compatible_with(value_tensor.shape)
    847       assign_op = gen_resource_variable_ops.assign_variable_op(
    848           self.handle, value_tensor, name=name)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py in assert_is_compatible_with(self, other)
   1115     """
   1116     if not self.is_compatible_with(other):
-> 1117       raise ValueError("Shapes %s and %s are incompatible" % (self, other))
   1118 
   1119   def most_specific_compatible_shape(self, other):

ValueError: Shapes (81, 512) and (149, 512) are incompatible

```

**Comment by ZDisket** [comment]
@jun-danieloh Which config did you initialize the Tacotron 2 with before loading weights?

**Comment by jun-danieloh** [comment]
These are all that I ran before getting errors.

```
import tensorflow as tf

import yaml
import numpy as np
import matplotlib.pyplot as plt

import IPython.display as ipd

from tensorflow_tts.inference import AutoConfig
from tensorflow_tts.inference import TFAutoModel
from tensorflow_tts.inference import AutoProcessor

tacotron2_config = AutoConfig.from_pretrained("../examples/tacotron2/conf/tacotron2.kss.v1.yaml")

tacotron2 = TFAutoModel.from_pretrained(
    config=tacotron2_config,
    pretrained_path=None,
    training=False, 
    name="tacotron2"
)

processor = AutoProcessor.from_pretrained("../tensorflow_tts/processor/pretrained/kss_mapper.json")
tacotron2.setup_window(win_front=10, win_back=10)
```

**Comment by jun-danieloh** [comment]
@ZDisket I `git clone` this repository just few days ago.

**Comment by dathudeptrai** [comment]
@jun-danieloh seem the weight have 149 charactor input embedding while kss have 81. Can you share me ur tacotron2_config when training ?

**Comment by jun-danieloh** [comment]
@dathudeptrai Your hack is working :) What do I need to have changes permanently in config setting? 

This is an yaml file for tacotron2_kss training. 
```
# This is the hyperparameter configuration file for Tacotron2 v1.
# Please make sure this is adjusted for the KSS dataset. If you want to
# apply to the other dataset, you might need to carefully change some parameters.
# This configuration performs 200k iters but 65k iters is enough to get a good models.

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################
hop_size: 256            # Hop size.
format: "npy"


###########################################################
#              NETWORK ARCHITECTURE SETTING               #
###########################################################
model_type: "tacotron2"

tacotron2_params:
    dataset: "kss"
    embedding_hidden_size: 512
    initializer_range: 0.02
    embedding_dropout_prob: 0.1
    n_speakers: 1
    n_conv_encoder: 5
    encoder_conv_filters: 512
    encoder_conv_kernel_sizes: 5
    encoder_conv_activation: 'relu'
    encoder_conv_dropout_rate: 0.5
    encoder_lstm_units: 256
    n_prenet_layers: 2
    prenet_units: 256
    prenet_activation: 'relu'
    prenet_dropout_rate: 0.5
    n_lstm_decoder: 1
    reduction_factor: 1
    decoder_lstm_units: 1024
    attention_dim: 128
    attention_filters: 32
    attention_kernel: 31
    n_mels: 80
    n_conv_postnet: 5
    postnet_conv_filters: 512
    postnet_conv_kernel_sizes: 5
    postnet_dropout_rate: 0.1
    attention_type: "lsa"

###########################################################
#                  DATA LOADER SETTING                    #
###########################################################
batch_size: 32             # Batch size.
remove_short_samples: true # Whether to remove samples the length of which are less than batch_max_steps.
allow_cache: true          # Whether to allow cache in dataset. If true, it requires cpu memory.
mel_length_threshold: 32   # remove all targets has mel_length <= 32 
is_shuffle: true           # shuffle dataset after each epoch.
use_fixed_shapes: false    # use_fixed_shapes for training (2x speed-up)
                           # refer (https://github.com/dathudeptrai/TensorflowTTS/issues/34#issuecomment-642309118)

###########################################################
#             OPTIMIZER & SCHEDULER SETTING               #
###########################################################
optimizer_params:
    initial_learning_rate: 0.001
    end_learning_rate: 0.00001
    decay_steps: 150000          # < train_max_steps is recommend.
    warmup_proportion: 0.02
    weight_decay: 0.001


###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 200000                 # Number of training steps.
save_interval_steps: 2000               # Interval steps to save checkpoint.
eval_interval_steps: 500                # Interval steps to evaluate the network.
log_interval_steps: 200                 # Interval steps to record the training log.
start_schedule_teacher_forcing: 200001  # don't need to apply schedule teacher forcing.
start_ratio_value: 0.5                  # start ratio of scheduled teacher forcing.
schedule_decay_steps: 50000             # decay step scheduled teacher forcing.
end_ratio_value: 0.0                    # end ratio of scheduled teacher forcing.
###########################################################
#                     OTHER SETTING                       #
###########################################################
num_save_intermediate_results: 1  # Number of results to be saved as intermediate results.
```
