### ISSUE TITLE
please give me a MB Melgan parmeters sugguestion.

### ISSUE THREAD

**Issue by PeijiYang** [TensorSpeech/TensorFlowTTS#528]
My datasets is 16 kHz, and i want set
```
fft_size=2048
hop_size=160
win_length=400
```
Can you give me some suggestion about how to set mbmelgan's parameters? 
```
upsample_scales: [2,4,5]

stft_loss_params:
    fft_lengths: [1024, 2048, 512]  # List of FFT size for STFT-based loss.
    frame_steps: [120, 240, 50]     # List of hop size for STFT-based loss
    frame_lengths: [600, 1200, 240] # List of window length for STFT-based loss.

subband_stft_loss_params:
    fft_lengths: [384, 683, 171]  # List of FFT size for STFT-based loss.
    frame_steps: [30, 60, 10]     # List of hop size for STFT-based loss
    frame_lengths: [150, 300, 60] # List of window length for STFT-based loss.
```
is this ok?
